#KDSK-107 관리자 로그인 기능 구성
DSC-University-of-Seoul/2021-spring-project pull request #107
Opened 2021-07-27 12:08 UTC by edit8080

# 기능 Issue
Feature Develop
Linked Feature backlog : #KDSK-107

## PR 목적

- 본 PR에서는 관리자 로그인 기능을 구현합니다.
   
## 작업 설명

1. 관리자 로그인 환경을 구성하기 위해 로그인 페이지를 구성합니다.
2. 서버와의 통신을 통해 사용자 인증 기능을 구성합니다.
3. DB 스키마의 User 테이블을 사용합니다.

## 라벨링 확인
작업 우선순위 : 중

2021-08-06 17:43 UTC, edit8080 commented
로그인 기능 구현 완료되었습니다.
아직 로그인 관련 백엔드가 미구현되어 테스트 데이터를 기반으로 작업하였습니다.
추후 연계 확인 후 발생하는 이슈를 해결할 예정입니다. 현재 추가된 기능은 다음과 같습니다.

1. 사용자 로그인 기능 및 페이지
2. 사용자 정보 변경 기능
3. 로그아웃
4. 헤더에 사용자 메뉴 추가

![image](https://user-images.githubusercontent.com/30149272/128550942-4d818319-5998-4c36-bbe4-4b2f53737ac3.png)

2021-08-07 07:59 UTC, handal95 requested changes
고생하셨습니다!
폴더 이름만 한번 더 확인 부탁드려요

2021-08-07 07:59 UTC, handal95 commented on app/src/modules/logs.js
> +import { dateUTCFormat, timeUTCFormat } from "../utils/format/format";
format directory에 있는 format 파일인가요??

2021-08-07 08:45 UTC, edit8080 commented on app/src/modules/logs.js
> +import { dateUTCFormat, timeUTCFormat } from "../utils/format/format";
넵 알겠습니다. Simple 작업 PR 하나 열어서 작업하겠습니다.

2021-08-07 08:47 UTC, handal95 approved these changes

2021-08-07 13:11 UTC, merged