#KDSK-121 제주시 seeder 삽입 후 연결 확인
DSC-University-of-Seoul/2021-spring-project pull request #124
Opened 2021-08-14 12:26 UTC by YubeenSon

# 기능 Issue
Linked Feature backlog : #KDSK- 121

## PR 목적

- 본 PR에서는 제주시 데이터 연결을 확인하기 위해서 제주시 데이터로 구성된 seeder를 삽입합니다.
   
## 작업 설명

- 제주시 데이터를 추가로 삽입합니다. 
- 한 테이블에 seeder 파일이 2개가 되어 rollback시 해당 파일의 seeder만 없어지도록 코드를 수정합니다.

## 라벨링 확인
작업 우선순위 : 중

2021-08-15 12:33 UTC, handal95 reviewed
test db에서 실제로 Up-down 반복해도 문제가 없나요??

2021-08-15 13:43 UTC, YubeenSon commented
@handal95 
한 테이블 대상으로 포맷을 적용해보고 결과를 확인한 후 파일들 수정하였습니다!(cctv 테이블은 up-down시 uuid가 변경되어서 위와 같이 테스트해보았습니다)
test db에서 다시 적용해볼까요..?:)

2021-08-15 14:04 UTC, handal95 requested changes

2021-08-15 14:04 UTC, handal95 commented on server/database/seeders/20210716132608-cctv.js
> +      center_id: ['11110000174', '11110000019', '11110000143'],
center_id가 11110000143인 데이터가 1곳 이상 들어있다면, 
위 upgrade로 추가되는 데이터 외에 기존 데이터까지 같이 모두 사라지게 될 것 같아요.

migration/seeder를 다룰때에는 up과 down이 정확히 반대 연산만 수행해야하는 만큼 
들어간 데이터만 역순서로 정확히 사라질 수 있도록 수정 부탁드려요.
아래 내용도 동일합니다.

2021-08-18 11:43 UTC, edit8080 reviewed
제주도 데이터 정상적으로 출력되는 모습 확인했습니다.
추가로, 기존에 이상이 있던 세종시 데이터도 정상적으로 출력되는 것을 확인했습니다.

![KakaoTalk_20210812_205537710](https://user-images.githubusercontent.com/30149272/129892301-563b4266-8ecc-4cb9-a064-e867d5b7e526.png)

![KakaoTalk_20210812_205559938](https://user-images.githubusercontent.com/30149272/129892305-c028c7c4-e378-46d9-b6b3-c68b824f36c6.png)

2021-08-18 11:43 UTC, edit8080 approved these changes

2021-08-20 13:44 UTC, handal95 commented on server/database/data_parsers/cctvs.js
> +const HEXADEMICAL = [1, 2, 3, 4, 5, 6, 7, 8, 9, 'A', 'B', 'C', 'D', 'E', 'F'];
함께 보시면 좋을 것 같습니다!
https://smart.science.go.kr/scienceSubject/maths/view.action?menuCd=DOM_000000101001006000&subject_sid=298

추가
https://www.youtube.com/watch?v=9Y7gAzTMdMA

2021-08-20 13:45 UTC, handal95 requested changes

2021-08-20 13:45 UTC, handal95 commented on server/database/data_parsers/cctvs.js
> +    macTemp.push(HEXADEMICAL[makeRandomNumber(15)]);
어? 15진수인가요?

2021-08-21 09:43 UTC, YubeenSon commented on server/database/data_parsers/cctvs.js
> +const HEXADEMICAL = [1, 2, 3, 4, 5, 6, 7, 8, 9, 'A', 'B', 'C', 'D', 'E', 'F'];
헣헣 확인하고 수정하였습니다~

2021-08-21 09:43 UTC, YubeenSon commented on server/database/data_parsers/cctvs.js
> +    macTemp.push(HEXADEMICAL[makeRandomNumber(15)]);
오타입니다

2021-08-21 09:45 UTC, YubeenSon commented on server/database/seeders/20210716132608-cctv.js
> +      center_id: ['11110000174', '11110000019', '11110000143'],
down시 PK를 매칭시키는 방법을 시도해보았습니다. 그러나 PK가 Auto Increment로 설정된 경우에는 고유값을 갖는 cctv_mac을 사용하거나, 시간의 흐름에 따라 해당 시간은 다시 기록되지 않을 테니 record_date, start_time과 같은 컬럼을 사용하였습니다.

2021-08-21 09:57 UTC, handal95 approved these changes

2021-08-21 09:57 UTC, handal95 commented on server/database/data_parsers/cctvs.js
> +function randomMac() {
randomMac 외에 다른 곳에서 사용되지 않으니까
내부로 이동시켜주시면 좋을 것 같습니다

2021-08-21 09:57 UTC, handal95 commented on server/database/data_parsers/cctvs.js
> +// console.log(cctvs);
안쓰는 코드 주석은 제거해도 괜찮을 것 같아요

2021-08-21 09:58 UTC, YubeenSon commented on server/database/data_parsers/cctvs.js
> +function randomMac() {
넵!

2021-08-21 09:59 UTC, YubeenSon commented on server/database/data_parsers/cctvs.js
> +// console.log(cctvs);
안 쓰는 부분 제거하고 필요한 부분은 살려두었습니다!

2021-08-21 10:00 UTC, merged